### ISSUE TITLE
Wrong scope for JUnit 4 dependency

### ISSUE THREAD

**Issue by pmwmedia** [tim-group/clocks#1]
The Maven artifact clocks-testing 1.0.1070 declares JUnit 4 as compile dependency:  http://central.maven.org/maven2/com/timgroup/clocks-testing/1.0.1070/clocks-testing-1.0.1070.pom

Actually, JUnit 4 is only used for testing. Therefore, I suggest to change the scope of JUnit 4 from `compile` to `test`. I use JUnit 5 for my JUnit tests, and I would prefer, if clocks-testing would not add JUnit 4 unnecessarily to the classpath.

**Comment by araqnid** [comment]
joda-testing has the same problem - that does in fact contain a JUnit4 rule, which should maybe be moved off into a separate artifact.

Anyway, version 1.0.1088 with this issue fixed is on its way to Maven Central now.

**Comment by pmwmedia** [comment]
That is great :) Thank you!

**Comment by araqnid** [comment]
Looks synced now https://repo1.maven.org/maven2/com/timgroup/clocks-testing/1.0.1088/clocks-testing-1.0.1088.pom
